image: node:latest

stages:
  - setup
  - test

install_dependencies:
  stage: setup
  script:
       - npm install
  artifacts:
	paths:
          - node_modules/
  
testing_testing:
  stage: test
  script: npm test
